# Generated by Django 2.2.10 on 2021-05-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalmedia',
            options={'verbose_name_plural': 'Digital Media'},
        ),
        migrations.AddField(
            model_name='borrowing',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Dikembalikan'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='tgl_peminjaman',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
