# Generated by Django 2.2.10 on 2021-05-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0002_auto_20210525_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='tgl_peminjaman',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='tingkat_member',
            field=models.CharField(choices=[('Golden', 'Golden'), ('Regular', 'Regular')], max_length=10),
        ),
    ]
