# Generated by Django 2.2.10 on 2021-05-25 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0003_auto_20210525_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='tgl_peminjaman',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='tgl_pengembalian',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
