# Generated by Django 2.2.10 on 2021-05-25 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perpus', '0004_auto_20210525_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='tgl_pengembalian',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
